package br.com.dio.app.repositories.presentation

import androidx.lifecycle.ViewModelProvider
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Toast
import br.com.dio.app.repositories.R
import org.koin.androidx.viewmodel.ext.android.viewModel

/**
 * Autogenerated HomeFragment with a ViewModel.
 *
 */
class HomeFragment : Fragment() {

    /**
     * Usa o delegate do Koin para injetar a dependência
     */
    val mViewModel: HomeViewModel by viewModel()



    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?,
    ): View? {


        /**
         * Observa o campo repo do ViewModel.
         */
        mViewModel.repo.observe(viewLifecycleOwner) {

        }

        return inflater.inflate(R.layout.home_fragment, container, false)


    }


    companion object {
        fun newInstance() = HomeFragment()
    }
}