package br.com.dio.app.repositories.presentation.ui.home

import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import br.com.dio.app.repositories.databinding.HomeFragmentBinding
import br.com.dio.app.repositories.presentation.adapter.RepoListAdapter
import org.koin.androidx.viewmodel.ext.android.viewModel

/**
 * Autogenerated HomeFragment with a ViewModel.
 *
 */
class HomeFragment : Fragment() {

    /**
     * Usa o delegate do Koin para injetar a dependência
     */
    val mViewModel: HomeViewModel by viewModel()
    val binding: HomeFragmentBinding by lazy {
        HomeFragmentBinding.inflate(layoutInflater)
    }
    val adapter = RepoListAdapter()


    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?,
    ): View? {


        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        mViewModel.getRepoList("chicorasia")
        binding.homeRepoRv.adapter = adapter

        /**
         * Observa o campo repo do ViewModel.
         */
        mViewModel.repo.observe(viewLifecycleOwner) {
            when(it){
                HomeViewModel.State.Loading -> {
                    // show progress bar...
                }
                is HomeViewModel.State.Error -> {
                    // show error messagem
                }
                is HomeViewModel.State.Success -> {
                    adapter.submitList(it.list)

                }
            }
        }
    }


    companion object {
        fun newInstance() = HomeFragment()
    }
}